# Generated by Django 4.1.1 on 2022-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='dd',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
