# Generated by Django 4.1.1 on 2022-12-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_login_user_dd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_user',
            name='dd',
        ),
    ]
