# Generated by Django 4.1.1 on 2022-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_remove_login_user_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
